name: Notify Unreleased PRs
on:
  workflow_dispatch:
  schedule:
    # Runs on Mondays at 8AM PST (15 UTC)
    - cron: '0 15 * * 1'

jobs:
  checking-pending-prs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - name: Install Dependencies
      run: npm ci
    - name: Check for PRs not yet released
      run: node ./bin/pending-prs.js --repos $NR_REPOS
      env:
        GITHUB_TOKEN: ${{ secrets.NODE_AGENT_GH_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
        NR_REPOS: ${{ secrets.NR_REPOS }}
